# Generated by Django 3.0.5 on 2020-05-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200501_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='user',
        ),
        migrations.AddField(
            model_name='access',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Access'),
        ),
    ]
