# Generated by Django 3.0.5 on 2020-05-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200501_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='username',
        ),
    ]
