# Generated by Django 3.0.5 on 2020-05-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200501_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Data collection sent', 'Data collection sent'), ('Data Received', 'Data Received'), ('Analysis', 'Analysis'), ('Final Pack Uploaded', 'Final Pack Uploaded')], max_length=30, null=True),
        ),
    ]
