# Generated by Django 3.0.5 on 2020-05-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_access_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='user',
        ),
    ]
