# Generated by Django 3.0.5 on 2020-05-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200501_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='user',
        ),
    ]
