# Generated by Django 3.0.5 on 2020-05-04 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_access_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CMs', to='base.Access'),
        ),
    ]
