# Generated by Django 3.0.5 on 2020-05-04 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20200504_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Access'),
        ),
    ]
