# Generated by Django 3.0.5 on 2020-05-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20200504_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='cm',
        ),
    ]
