# Generated by Django 3.0.5 on 2020-05-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20200505_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='cm',
            new_name='username',
        ),
    ]
