# Generated by Django 3.0.5 on 2020-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_account_finalpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='filledDataCollection',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
