# Generated by Django 3.0.5 on 2020-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_account_gap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gap',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=30, null=True),
        ),
    ]
