# Generated by Django 3.0.5 on 2020-06-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20200531_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('Data collection sent', 'Data collection sent'), ('Data Received', 'Data Received'), ('Analysis', 'Analysis'), ('Final Pack Uploaded', 'Final Pack Uploaded')], max_length=30, null=True),
        ),
    ]
